version: "3"
services:
  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=coconut
    ports:
      - "3306:3306"
  cache:
    image: redis
    ports:
      - "6379:6379"
  backend:
    image: coconut-backend
    ports:
      - "8000:8000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/coconut?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=America/New_York&allowPublicKeyRetrieval=true
      - SPRING_REDIS_HOST=cache
    restart: on-failure
  frontend:
    image: coconut-frontend
    ports:
      - "8080:8080"
  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node